### ISSUE TITLE
SASL EXTERNAL and expired certificates

### ISSUE THREAD

**Issue by Olathe** [irssi/irssi#560] opened 2016-10-21 01:58 UTC
`SASL EXTERNAL` uses a certificate file to prove who I am to the IRC server. Unfortunately, certificate files can expire. When this happens, the only thing I see when connecting is an uninformative message from the server that SASL failed with no reason why.

Because this happens out of the blue after SASL has been working properly for weeks or months, it can be quite difficult or even impossible to identify the source of the problem. It would be nice if `irssi` gave an error message if the certificate file had expired.

**Comment by dequis** [comment] 2016-10-21 02:38
Duplicate of #211

**Closed by dequis** 2016-10-21 02:38 UTC
