### ISSUE TITLE
Bug in the hilight code in combination with ACTIONS and color codes

### ISSUE THREAD

**Issue by incognico** [irssi/irssi#31] opened 2014-06-15 11:24 UTC
When you are hilighted in an ACTION and there are color codes before your nickname and there is a comma after your nickname, weird stuff happens: the text is grey after the hilighed part. I don't exactly remember if bold formatting plays a role but I remember that I discussed this issue with someone on IRC and he told me that this is a very ugly bug in the very tricky hilight code :-)

![capture](https://cloud.githubusercontent.com/assets/2098066/3280794/75c9ce76-f47e-11e3-9a19-d84e20877189.PNG)

**Comment by ailin-nemui** [comment] 2015-09-18 21:57
closing as duplicate of #95

**Closed by ailin-nemui** 2015-09-18 21:57 UTC
