### ISSUE TITLE
Does not fall back to to IPv4 address if IPv6 address is unreachable

### ISSUE THREAD

**Issue by madduck** [irssi/irssi#641] opened 2017-02-07 20:31 UTC
This is [FS#579](https://github.com/irssi-import/bugs.irssi.org/issues/579) carried over from #26:

    resolve_prefer_ipv6 = ON
    Irssi: Looking up irc.oftc.net
    Irssi: Connecting to irc.oftc.net [2605:bc80:3010:101:0:2:0:6667] port 6697
    Irssi: Unable to connect server irc.oftc.net port 6697 [Network is unreachable]
    resolve_prefer_ipv6 = OFF
    Irssi: Looking up irc.oftc.net
    Irssi: Connecting to irc.oftc.net [2600:3c03::f03c:91ff:fe96:35cd] port 6697
    Irssi: Unable to connect server irc.oftc.net port 6697 [Network is unreachable]

The `resolve_prefer_ipv6` setting — also subject of #190 — is not really relevant here. The problem is that for chat servers that advertise `AAAA` records in DNS, unless Irssi can establish an IPv6 connection to the server, the connection fails. The only way to get it to work is to use `/connect -4`.

The correct behaviour with `getaddrinfo()` (which respects the lookup order defined in `/etc/gai.conf`) would be for Irssi to fall back to using the IPv4 address, if such is advertised (which it is in this case).

**Comment by ailin-nemui** [comment] 2019-12-15 17:57
@madduck do you want to test #1146

**Comment by madduck** [comment] 2019-12-16 18:14
Hey @ailin-nemui, sure thing I'll test it, but not until after the silly holidays coming up. However, I am also a little concerned about the kludge that's being proposed, vs. the `getaddrinfo` implementation…

**Comment by slingamn** [comment] 2019-12-29 03:35
As the author of the patch, I concede that it's a kludge, but I don't think there's a easy solution that improves on it, certainly not of the form "make better use of `getaddrinfo`".

As noted on the PR, irssi is already using `AI_ADDRCONFIG`. The problem is that `getaddrinfo` does not detect conditions where there is a valid IPv6 address, but no IPv6 WAN connectivity --- this is not detected until a connection attempt fails.

There are two non-kludge suggestions listed in the PR comments, but they both require some form of major surgery.

**Comment by madduck** [comment] 2019-12-29 05:05
> The problem is that `getaddrinfo` does not detect conditions where there is a valid IPv6 address, but no IPv6 WAN connectivity --- this is not detected until a connection attempt fails.

I don't see any other way to handle this, and I don't understand why most other software can deal with this, but `irssi` cannot?

**Comment by slingamn** [comment] 2019-12-29 14:01
>I don't see any other way to handle this

You mean, no way other than attempting to connect and failing? If so, I agree.

The architectural problem with irssi right now is that it doesn't maintain any state between invocations of `getaddrinfo` --- the state machine goes straight from "resolve the name to some arbitrarily chosen address" to "attempt to connect to that address". This also implies that irssi is totally reliant on round-robin DNS for routing around failed servers --- the only mechanism for routing around a failed server is to keep resolving until one of the non-failed servers happens to be first in the list.

The recommended solution to this problem is Happy Eyeballs, which is [highly nontrivial](https://daniel.haxx.se/blog/2012/01/03/getaddrinfo-with-round-robin-dns-and-happy-eyeballs/) to add to a conventional async application. The second-best solution, as mentioned in the PR comments, is to add a new state to irssi's state machine, where it attempts to connect to every resolved address without any delays/backoff. I didn't feel like I understood the codebase well enough to attempt this solution, but if you have strong feelings, I can try.

**Closed** 2020-01-06 09:42 UTC
Labels: ipv6
