### ISSUE TITLE
"/win list" only handles three digits.

### ISSUE THREAD

**Issue by KindOne-** [irssi/irssi#223] opened 2015-02-14 20:55 UTC
The ```/win list``` can only handle three characters for the windows number before the fourth digit is chopped off.
```text
15:34:01 Ref Name                 Active item     Server          Level
15:34:01 1   (status)                             freenode        ALL
...
15:34:01 998                      ChanServ        freenode
15:34:01 999                      MemoServ        freenode
15:34:01 100                      NickServ        freenode
15:34:01 100                      *status         freenode
15:34:01 100                      *status         freenode_testne
```

**Comment by ahf** [comment] 2015-02-14 21:02
I've met many people who are in a lot of channels, but you have beaten all of them! :-)

**Comment by ailin-nemui** [comment] 2015-02-16 07:51
not a bug, just update the format as required

**Comment by dequis** [comment] 2015-02-16 21:10
So:

`/format windowlist_line %#$[3]0 %|$[20]1 $[15]2 $[15]3 $4` - default value

Could avoid the truncation by using `[!3]` instead of `[3]`

`/format windowlist_line %#$[!3]0 %|$[20]1 $[15]2 $[15]3 $4`

Which would result in something like this (note how they stop being aligned after 999)

```
15:34:01 Ref Name                 Active item     Server          Level
15:34:01 1   (status)                             freenode        ALL
15:34:01 2                        something       something
...
15:34:01 998                      ChanServ        freenode
15:34:01 999                      MemoServ        freenode
15:34:01 1001                      NickServ        freenode
15:34:01 1002                      *status         freenode
15:34:01 1003                      *status         freenode_testne
```

@ahf, choose:

 * Close this, have @KindOne- edit the format settings, forget about it
 * Fix it in the default settings

**Comment by ahf** [comment] 2015-04-08 01:12
Fix it in the default settings! :-P

**Comment by GeertHauwaerts** [comment] 2015-06-12 19:15
with proper alignment ;)

**Closed** 2015-06-12 19:14 UTC
Labels: bug
