### ISSUE TITLE
Binding meta-O causes arrow keys to stop working

### ISSUE THREAD

**Issue by ahihi** [irssi/irssi#430] opened 2016-02-29 23:07 UTC
I am using `/bind meta-O change_window 49`. In irssi 0.8.17 and earlier this works fine, but in 0.8.18 my arrow keys stop functioning normally — they insert ABCD characters instead.

A fresh config plus this binding suffices to reproduce the issue.

**Comment by ailin-nemui** [comment] 2016-02-29 23:09
that's a technical limitation on the one hand. Irssi 0.8.18 now enabled application keypad which makes your arrow keys send SS3-{A,B,C,D} (a change from the previous CSI) SS3 is one of the common control sequence initiators and translates to Esc, O (which is the same as your Alt+O) (CSI=Esc,[)

**Comment by ailin-nemui** [comment] 2016-03-02 10:13
for now I would suggest the following work-around in your startup file and being aware that there are two different control sequence styles (of which one will occupy Alt+Shift+O):
```
script exec print STDERR `tput rmkx`
```

I'm not sure if this can be fixed in any other way

**Comment by ailin-nemui** [comment] 2016-03-02 10:26
@LemonBoy b5b73cb471e5dff6f8c872071c7cb8678e4142ea is causing this regression, what are the pros and cons of KX? maybe it's better to stick to non-kx?

**Comment by stintel** [comment] 2016-03-14 18:08
Running into this issue as well. In fact, everybody using https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/keybinds.pl has "BIND meta-O change_window 39". Thanks for the workarounds, but as this is a regression (and quite the annoying one), I would like to see this fixed.

**Comment by LemonBoy** [comment] 2016-03-14 18:22
I am able to bind whatever command I want to meta-o, I think the problem lies in your terminals (or fingers)

**Comment by dequis** [comment] 2016-03-14 18:31
@LemonBoy uppercase O, not lowercase

**Comment by LemonBoy** [comment] 2016-03-14 18:34
Both `meta-o` and `meta-O` work just well in `urxvt` and `xterm`

**Comment by ailin-nemui** [comment] 2016-03-14 19:00
but it conflicts with up-arrow (now) because that also starts with meta-O

**Comment by trou** [comment] 2016-03-15 00:02
Chiming in : I'm bitten by the bug and I'd like it to be fixed.

**Comment by ailin-nemui** [comment] 2016-03-22 15:57
since there were very vocal people about meta-O I expect that @stintel @rhonda @trou and @ahf test #459 otherwise I don't see the point of adding that into 0.8.18a

**Comment by stintel** [comment] 2016-03-23 04:39
After "/set term_appkey_mode off" with changes from #459 I no longer have this issue. Thanks!

**Closed** 2016-03-24 13:52 UTC
Labels: question
