### ISSUE TITLE
Find a less-global method of deciding when to print netsplits/mode/joins

### ISSUE THREAD

**Issue by GinjaNinja32** [irssi/irssi#420] opened 2016-02-10 10:45 UTC
When irssi is looking for more netsplit QUITs, more MODEs, etc, _any_ printed text to _any_ window will cause the accumulated QUITs/MODEs/etc to be printed; I have a window set up as a 'raw' window, printing exactly what irssi receives from connected servers, with no processing. My script to do so currently requires stopping the "print starting" signal while I'm trying to print;

``` perl
Irssi::signal_add_first("print starting", "ignore_signal");
$window->print($text, MSGLEVEL_NEVER) if ($window);
Irssi::signal_remove("print starting", "ignore_signal");
```

If I don't have this in place, the result is one netsplit line for every user, printed immediately (because my 'raw' script has printed to my raw-input window, causing netsplit detection to conclude the end of the splitting users):

```
-!- Netsplit *.net <-> *.split quits: SomeUser
-!- Netsplit *.net <-> *.split quits: AnotherUser
-!- Netsplit *.net <-> *.split quits: SomeOtherUser
```

Could this be done in a way that it doesn't rely on watching for printed text? Perhaps if the server sends something that is _not_ another QUIT/MODE/etc?

**Comment by LemonBoy** [comment] 2016-02-29 21:14
I agree it *shouldn't* absolutely hook the `print starting` signal, but I can't think of another way to solve this than to print the `parts` minus `joins` after the netsplit is over (after the timer runs out) but that way you don't get any feedback in case the person you're talking with has been split (in half ?)

**Comment by ailin-nemui** [comment] 2016-02-29 21:53
it could be done more granular for example on a server/channel flag and/or excluding certain message levels. could be much effort...

**Comment by dequis** [comment] 2017-03-11 22:11
Can we consider this fixed by #465?

**Comment by dequis** [comment] 2018-01-14 20:34
So this goes back to unfixed.

PR #465 tried to fix this

Issue #567 was a regression from that fix

PR #577 fixed that regression

Issue #809 appeared much later and its cause is still not fully understood.

PR #812 reverted most of the original fix (made the filtering a no-op)

So to get this done we have to figure out a fix to #809 that isn't a revert.

**Comment by ailin-nemui** [comment] 2018-01-14 21:56
one thing I noticed

https://github.com/irssi/irssi/blob/7de1378dab8081932d9096e19ae3d0921e560230/src/fe-common/irc/fe-netsplit.c#L111
here the whole split is marked as printed. note how this gets triggered even when you try to filter out a single channel for display; it would need to be done per channel

**Comment by ailin-nemui** [comment] 2018-02-16 14:47
fixed according to @GinjaNinja32 , reopen when this turns out to be wrong

**Closed by ailin-nemui** 2018-02-16 14:47 UTC
Labels: enhancement

**Comment by dequis** [comment] 2018-02-16 14:49
Wait, what? The current code has most of the filtering disabled

**Comment by dequis** [comment] 2018-02-16 15:19
> 11:49 < dx> ...i should look here before commenting on github
> 11:50 < dx> i don't know what "a while" is but we reverted all of this code very recently
> 11:51 < Nei[e]> I think he's running git
> 11:51 < dx> the current code has one check, sure, but it's a tiny subset of what was checked before
> 11:52 < Nei[e]> probably that;s all it took
> 11:52 < GinjaNinja32> dx: my original issue is fixed; the current code may not be perfect, but the reason I opened that issue is gone
> 11:53 < GinjaNinja32> previously my $window->print() would make irssi decide the netsplit was lots of little netsplits unless I ignored "print starting"
> 11:53 < dx> GinjaNinja32: oh! you had a script that broke it?
> 11:54 < Nei[e]> see the original issue report :)
> 11:54 < GinjaNinja32> I have a script that prints every incoming line to a window called "raw" that sorts (chansort.pl) at the end of my window list
> 11:54 < dx> it's been so long
> 11:54 < GinjaNinja32> useful for diagnosing weird issues sometimes
> 11:55 < dx> and IMO we shouldn't aim to fix just that niche use case
> 11:55 < GinjaNinja32> when I originally wrote it I needed to signal_add_first() something to ignore "print starting", or irssi would print separate lines for each user who split
> 11:55 < dx> on the other hand i don't want to deal with subtle netsplit related issues anymore so maybe it's better to claim it's done with this
