### ISSUE TITLE
Fix current default nick highlighting behaviour

### ISSUE THREAD

**Issue by ahf** [irssi/irssi#221] opened 2015-02-11 21:50 UTC
It's odd! People shouldn't have to do anything to make their client highlight on their nickname anywhere in the string.

**Comment by dgl** [comment] 2015-02-12 01:34
I think people should have a choice. (e.g. someone using a nick which is a
common first name may not want to be highlighted when someone mentions that
name).

Random proposal:
- Add a -expand option to /hilight
- Ship with a default config which includes a /hilight -expand -full $N

(The advantages being this doesn't change behaviour for existing users and
users can also delete this.)

**Comment by ailin-nemui** [comment] 2015-02-12 11:30
it's not odd, there is a convention of explicitly addressing someone when starting the line with that nick, in comparison to just talking about someone

**Comment by barul42** [comment] 2015-02-12 11:38
On 2015-02-11 22:50, Alexander Færøy wrote:
> It's odd! People shouldn't have to do anything to make their client
> highlight on their nickname anywhere in the string.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/irssi/irssi/issues/221
I think it's normal; one should be hilighted when someone explicitly 
talks to him, not when someone speaks about him.
Also, /hilight $nick isn't a too long command to type :)
-- 
barul

**Comment by ilbelkyr** [comment] 2015-02-12 12:39
Many people want to be highlighted even when they're being talked *about*, though. From what I've seen, it's what people *expect*. Of course, the current behaviour should still be available somehow.

Additionally, people often talk to each other without putting the nick first. Think "thanks bcode" and the like.

> Also, /hilight $nick isn't a too long command to type :)

But currently, you need to do that for every nick you use. I occasionally use some nicks that happen to be common words, so I'd like to avoid highlighting on them while I'm not actively using them, too.

**Comment by dequis** [comment] 2015-02-12 13:09
I like dgl's idea of `/hilight -expand -full $N`, also solves the problem about needing to add one highlight for each different nick, and would only apply to the current one (if the expansion is done while matching)

**Comment by weedy** [comment] 2015-02-24 09:50
Duplicate of #56

**Comment by flaw600** [comment] 2015-05-30 07:33
Idk if this is is the issue being referred to now, but I agree that users expect that highlighting will work when the nick is anywhere in the string. Indeed, judging from speaking to various IRCers using various clients (console, GUI, web, etc.), irssi is one of the few, if not only, clients that doesn’t already do this. I can understand how this might not be the default config, but it should be an easy option. I like @dgl ’s idea of the expansion. I know that I, for one, miss a lot of conversation directed at me because others think I was tagged when irssi doesn’t recognize it.

**Comment by ailin-nemui** [comment] 2015-09-18 22:02
closing as duplicate of #56

**Closed by ailin-nemui** 2015-09-18 22:02 UTC
Labels: bug, enhancement
