### ISSUE TITLE
Hilights don't work when the message is sent to @#channel

### ISSUE THREAD

**Issue by dwfreed** [irssi/irssi#891] opened 2018-06-29 09:22 UTC
I'm on b382bd1 for vague's hidden ignores, and hilights aren't applying to messages sent to @#channel.  I don't recall if they worked correctly on 1.1 or not.

**Comment by dcollinsn** [comment] 2019-09-28 23:01
I believe this is a dupe of #354 ?

**Comment by ailin-nemui** [comment] 2019-10-15 13:14
@dwfreed can you see if this was fixed by #1129

**Closed** 2020-03-17 01:11 UTC
Labels: bug
