### ISSUE TITLE
/connect clears screen

### ISSUE THREAD

**Issue by macshaggy** [irssi/irssi#523] opened 2016-08-06 14:42 UTC
IRSSI is still running but I can't see anything connection information at all. Currently, I'm running on OS X with --with-dante flag. 

I try to connect to a server and the screen blanks and I see the command line but it still looks like I am connected to the client just not the server. But I can't see anything from within the client.
![client-look](https://cloud.githubusercontent.com/assets/796886/17457309/7cecc3ae-5bc2-11e6-9ebf-4688c04cb02d.png)

**Comment by dequis** [comment] 2016-08-06 18:48
Hahah oh wow interesting coincidence, i was just asking about the dante support on irc a while ago and said something along the lines of "it broke the UI once for some guy using OS X"

And when I check the github notifications there's someone who enabled socks, uses OS X, and has a broken UI. Hi there!

Anyway yeah, it's broken. Don't enable socks.

Closing as duplicate of #266

**Closed by dequis** 2016-08-06 18:48 UTC

**Comment by macshaggy** [comment] 2016-08-06 19:03
Gotcha!!

I'll try again.

Jason K Bellew
@theshaggyviking
