### ISSUE TITLE
Freedesktop Base Directory Compile Flag

### ISSUE THREAD

**Issue by SoniEx2** [irssi/irssi#847] opened 2018-02-13 21:44 UTC
I'd like a compile flag to enable freedesktop base directory compliance.

**Comment by vague666** [comment] 2018-02-13 21:45
Nothing stops you from starting irssi with --home ~/.config/irssi

**Comment by SoniEx2** [comment] 2018-02-13 21:49
That's not what it's for.

My distro already has `python` = 3, for example. It would be nice to have XDG as the default, too, even if the official devs and every other distro would prefer non-XDG by default.

**Comment by ailin-nemui** [comment] 2018-02-14 07:43
it's more complicated, .irssi would have to be split into local/share, config and cache

**Comment by ailin-nemui** [comment] 2018-02-14 07:46
Duplicate of #51  #157  #511

**Closed by ailin-nemui** 2018-02-14 07:46 UTC

**Comment by SoniEx2** [comment] 2018-02-14 10:21
Yes, so get a compile flag.
