### ISSUE TITLE
dcc_autoget does not work in irssi 1.0.1

### ISSUE THREAD

**Issue by slashbeast** [irssi/irssi#670] opened 2017-03-11 14:17 UTC
I just noticed that my irssi no longer automatically accept the DCC file transfer, even that I have the dcc_autoget=ON.

    15:11 DCC SEND from ZZZ [xx.xx.xx.xx port 24725]: foo [283MB]
    15:11 DCC no file offered by ZZZ

And as that, i need to run '/dcc get' to accept the transfer.

I am running irssi-1.0.1. Downgrade to irssi-0.8.21 makes the autoget working.

**Comment by LemonBoy** [comment] 2017-03-11 14:18
Closed as duplicate of #656. This has already been fixed in the `master` branch.

**Closed by LemonBoy** 2017-03-11 14:18 UTC

**Comment by ailin-nemui** [comment] 2017-03-12 11:28
please try 1.0.2
