### ISSUE TITLE
Regexp-style values not properly escaped when /SAVEing to config

### ISSUE THREAD

**Issue by madduck** [irssi/irssi#642] opened 2017-02-09 04:12 UTC
My `print_signals.pl` script allows the user to specify regexps using /SET. Unfortunately, these are not properly escaped when saved to config. For instance:

     /set print_signals_limit_regexp ^$

yields

    print_signals_limit_regexp = "^$";

and having that in the configuration file actually segfaults irssi:

    09 04:34 Irssi: Looking up chat.freenode.net
    09 04:34 Irssi: Connecting to chat.freenode.net [130.239.18.119] port 7000

    [madduck][1:freenode]
    [(status)] zsh: segmentation fault  irssi -!

    irssi[2894]: segfault at ff00000012 ip 00007fdce0e9da54 sp 00007ffe40171840 error 4 in libperl.so.5.20.2[7fdce0dc5000+1b7000]

If I remove the setting, irssi works just fine again.

I've not been able to dig deeper yet…

**Comment by dequis** [comment] 2017-02-09 04:40
Bug in your scripts. Remove all scripts, try again, add one by one, isolate the buggy one.

Also, get a backtrace with gdb or whatever.

**Comment by madduck** [comment] 2017-02-09 07:50
I am sure it has to do with `print_signals.pl`, but I fail to see the bug in the script. I'll provide gdb etc. shortly.

Meanwhile, I just want to note that if I insert a simple

    print STDERR $limitre;

at https://github.com/irssi/scripts.irssi.org/blob/master/scripts/print_signals.pl#L56, then there is no segfault. So this seems to be one of those weird bugs where timing matters, but it might very well be in the signal emission code within irssi…

**Comment by dequis** [comment] 2017-02-10 17:53
Closing since this doesn't seem to be a problem with irssi itself. Reopen if you can reproduce and have a gdb or valgrind log. Perl scripts are known to not be memory safe and there are many ways to crash irssi from perl, so unless we have something concrete here there's not much to do.

**Closed by dequis** 2017-02-10 17:53 UTC
