### ISSUE TITLE
ssl passphrase support

### ISSUE THREAD

**Issue by darix** [irssi/irssi#103] opened 2014-07-20 13:25 UTC
I am not sure that saving the password in plain text in the irssi config kind of defeats the purpose of the password in first place. openSUSE had a patch that always asked for the passphrase but then would of course block in the reconnect case. not ideal either.

how about asking on the first connect and caching the passphrase in memory?
and maybe give the passphrase dialog a timeout.

sounds better than storing it in plaintext.

**Comment by ailin-nemui** [comment] 2015-09-18 21:36
closing this for now duplicate of #6

**Closed by ailin-nemui** 2015-09-18 21:36 UTC
