### ISSUE TITLE
Store password out of config.

### ISSUE THREAD

**Issue by eloyesp** [irssi/irssi#246] opened 2015-05-12 19:48 UTC
I'm trying to publish my irssi config file without compromising my passwords. (very similar to [those][1] [questions][2]). The best solution I thought is to use the `.netrc` file that can be easily read from [perl][4].

My first idea was to make a script that listen to the "server connecting" signal, and if the password equals 'netrc' then it stop the signal and start a new connection (but with the new password). The issue is that the connection [doesn't wait for the signal][5] to be accepted and do not care what happened with the signal (so I cannot change the password from the script). The [gist for the script][6] I've used to test, the connection pass without any change.

As I see, there are to possible implementations. One is to break the `server_real_connect` in two parts: one that just emit the signal and the second that do the actual connection, or make the `signal_emit` function return non 0 if the signal was stopped.

Regards.

 [1]: http://superuser.com/questions/594554/separate-irssi-services-passwords-from-main-configuration-file
 [2]: http://superuser.com/questions/895185/how-to-store-confidential-info-whilst-using-dot-files-framework
 [4]: http://perldoc.perl.org/Net/Netrc.html
 [5]: https://github.com/irssi/irssi/blob/master/src/core/servers.c#L215
 [6]: https://gist.github.com/eloyesp/fb31135b22d44904da2e

**Comment by dequis** [comment] 2015-05-12 23:41
Duplicate of #6?

**Comment by MasterRoot24** [comment] 2015-05-13 08:29
Is a simpler solution not just to allow files to be included in the irssi config files. That would allow one to version control their config file and in this file include a separate, secured file which contains only passwords which is not committed to version control.

**Comment by ailin-nemui** [comment] 2015-05-13 12:10
the current Perl API does not allow any modification of struct entries (they are just copies)

**Comment by dequis** [comment] 2015-09-18 22:03
Closing as duplicate of #6 since i can now close things as duplicate of #6

(unless someone disagrees with me that they are the same issue)

**Closed by dequis** 2015-09-18 22:03 UTC
