### ISSUE TITLE
wrong date printed on day change sometimes

### ISSUE THREAD

**Issue by Soundtoxin** [irssi/irssi#1219] opened 2020-08-29 07:53 UTC
```
Day changed to 27 Aug 2020
Day changed to 02 Jul 2020
Day changed to 22 Aug 2020
```
Here's a chat window left open I haven't used in a  few days... The date of the 27th is correct, the next two are wrong. They should say 28 and 29 Aug 2020.

Here's an excerpt from another chat with the in-between messages trimmed out:
```
Day changed to 07 Aug 2020
Day changed to 08 Aug 2020
Day changed to 01 Aug 2020
Day changed to 19 Jul 2020
Day changed to 09 Aug 2020
Day changed to 10 Aug 2020
Day changed to 10 Aug 2020
Day changed to 12 Aug 2020
Day changed to 05 Jul 2020
Day changed to 16 Aug 2020
Day changed to 17 Aug 2020
Day changed to 18 Aug 2020
Day changed to 17 Aug 2020
Day changed to 20 Aug 2020
Day changed to 21 Aug 2020
Day changed to 22 Aug 2020
Day changed to 20 Aug 2020
Day changed to 23 Aug 2020
Day changed to 25 Aug 2020
Day changed to 26 Aug 2020
Day changed to 14 Aug 2020
Day changed to 28 Aug 2020
Day changed to 29 Aug 2020
```

The date is both sometimes many days too early and sometimes reuses a number.

Here's my version:
`-!- Irssi: Client: irssi 1.3-dev-296-g964c067b-dirty (20200617 1357)`

I built my own irssi some time ago to avoid the ctrl-space hanging bug. I think this date problem has been happening for a while. Probably the whole time, but I only notice occasionally.

**Comment by dwfreed** [comment] 2020-08-29 08:01
Duplicate of #1207, fixed by #1208

**Closed by dwfreed** 2020-08-29 08:01 UTC
